<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlumniSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('alumni')->insert([
            [
                'nim' => '062040831000',
                'nama' => 'Ahmad Fauzi',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2002-05-15',
                'email' => 'ahmadfauzi@gmail.com',
                'telepon' => '081234567890',
                'alamat' => 'Jl. Merdeka No. 10, Jakarta',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.75,
                'nomor_ijazah' => '2020-MI-D3-1000'
            ],
            [
                'nim' => '062040831001',
                'nama' => 'Budi Santoso',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-08-22',
                'email' => 'budisantoso@gmail.com',
                'telepon' => '081234567891',
                'alamat' => 'Jl. Sudirman No. 25, Bandung',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.60,
                'nomor_ijazah' => '2020-MI-D3-1001'
            ],
            [
                'nim' => '062040831002',
                'nama' => 'Citra Dewi',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-03-10',
                'email' => 'citradewi@gmail.com',
                'telepon' => '081234567892',
                'alamat' => 'Jl. Asia Afrika No. 40, Surabaya',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.85,
                'nomor_ijazah' => '2020-MI-D3-1002'
            ],
            [
                'nim' => '062040831003',
                'nama' => 'Dewi Lestari',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-01-05',
                'email' => 'dewilestari@gmail.com',
                'telepon' => '081234567893',
                'alamat' => 'Jl. Gajah Mada No. 12, Yogyakarta',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.90,
                'nomor_ijazah' => '2020-MI-D3-1003'
            ],
            [
                'nim' => '062040831004',
                'nama' => 'Eko Prasetyo',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-11-29',
                'email' => 'ekoprasetyo@gmail.com',
                'telepon' => '081234567894',
                'alamat' => 'Jl. Pahlawan No. 7, Semarang',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.55,
                'nomor_ijazah' => '2020-MI-D3-1004'
            ],
            [
                'nim' => '062040831005',
                'nama' => 'Fajar Ramadhan',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2002-07-19',
                'email' => 'fajarramadhan@gmail.com',
                'telepon' => '081234567895',
                'alamat' => 'Jl. Diponegoro No. 30, Malang',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.70,
                'nomor_ijazah' => '2020-MI-D3-1005'
            ],
            [
                'nim' => '062040831006',
                'nama' => 'Gita Permata',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-04-01',
                'email' => 'gitapermata@gmail.com',
                'telepon' => '081234567896',
                'alamat' => 'Jl. Ahmad Yani No. 50, Medan',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.92,
                'nomor_ijazah' => '2020-MI-D3-1006'
            ],
            [
                'nim' => '062040831007',
                'nama' => 'Hadi Susanto',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-09-14',
                'email' => 'hadisusanto@gmail.com',
                'telepon' => '081234567897',
                'alamat' => 'Jl. Gatot Subroto No. 18, Palembang',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.68,
                'nomor_ijazah' => '2020-MI-D3-1007'
            ],
            [
                'nim' => '062040831008',
                'nama' => 'Indah Sari',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-06-25',
                'email' => 'indahsari@gmail.com',
                'telepon' => '081234567898',
                'alamat' => 'Jl. Thamrin No. 5, Makassar',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.80,
                'nomor_ijazah' => '2020-MI-D3-1008'
            ],
            [
                'nim' => '062040831009',
                'nama' => 'Joko Santoso',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2003-02-08',
                'email' => 'jokosantoso@gmail.com',
                'telepon' => '081234567899',
                'alamat' => 'Jl. Kebon Jeruk No. 22, Bogor',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2023,
                'ipk' => 3.72,
                'nomor_ijazah' => '2020-MI-D3-1009'
            ],
            [
                'nim' => '062040841000',
                'nama' => 'Karenina Putri',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2001-05-20',
                'email' => 'kareninaputri@gmail.com',
                'telepon' => '081300000000',
                'alamat' => 'Jl. Kenanga No. 15, Jakarta',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.88,
                'nomor_ijazah' => '2020-MI-D4-1000'
            ],
            [
                'nim' => '062040841001',
                'nama' => 'Leonardi Wijaya',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2002-09-11',
                'email' => 'leonardiwijaya@gmail.com',
                'telepon' => '081300000001',
                'alamat' => 'Jl. Melati No. 8, Bandung',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.70,
                'nomor_ijazah' => '2020-MI-D4-1001'
            ],
            [
                'nim' => '062040841002',
                'nama' => 'Monica Halim',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-01-28',
                'email' => 'monicahalim@gmail.com',
                'telepon' => '081300000002',
                'alamat' => 'Jl. Anggrek No. 22, Surabaya',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.91,
                'nomor_ijazah' => '2020-MI-D4-1002'
            ],
            [
                'nim' => '062040841003',
                'nama' => 'Nathaniel Putra',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-03-05',
                'email' => 'nathanielputra@gmail.com',
                'telepon' => '081300000003',
                'alamat' => 'Jl. Dahlia No. 17, Yogyakarta',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.65,
                'nomor_ijazah' => '2020-MI-D4-1003'
            ],
            [
                'nim' => '062040841004',
                'nama' => 'Olivia Chandra',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-07-13',
                'email' => 'oliviachandra@gmail.com',
                'telepon' => '081300000004',
                'alamat' => 'Jl. Edelweiss No. 9, Semarang',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.95,
                'nomor_ijazah' => '2020-MI-D4-1004'
            ],
            [
                'nim' => '062040841005',
                'nama' => 'Peter Wijaya',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2003-04-29',
                'email' => 'peterwijaya@gmail.com',
                'telepon' => '081300000005',
                'alamat' => 'Jl. Gardenia No. 2, Malang',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.78,
                'nomor_ijazah' => '2020-MI-D4-1005'
            ],
            [
                'nim' => '062040841006',
                'nama' => 'Queenisha Zahra',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2001-10-02',
                'email' => 'queenishazahra@gmail.com',
                'telepon' => '081300000006',
                'alamat' => 'Jl. Tulip No. 33, Medan',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.82,
                'nomor_ijazah' => '2020-MI-D4-1006'
            ],
            [
                'nim' => '062040841007',
                'nama' => 'Ryan Setiawan',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2002-08-16',
                'email' => 'ryansetiawan@gmail.com',
                'telepon' => '081300000007',
                'alamat' => 'Jl. Bougenville No. 11, Palembang',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.69,
                'nomor_ijazah' => '2020-MI-D4-1007'
            ],
            [
                'nim' => '062040841008',
                'nama' => 'Sonia Permata',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-06-07',
                'email' => 'soniapermata@gmail.com',
                'telepon' => '081300000008',
                'alamat' => 'Jl. Cempaka No. 45, Makassar',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.90,
                'nomor_ijazah' => '2020-MI-D4-1008'
            ],
            [
                'nim' => '062040841009',
                'nama' => 'Tommy Hartono',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-02-20',
                'email' => 'tommyhartono@gmail.com',
                'telepon' => '081300000009',
                'alamat' => 'Jl. Kamboja No. 6, Bogor',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2020,
                'tahun_lulus' => 2024,
                'ipk' => 3.73,
                'nomor_ijazah' => '2020-MI-D4-1009'
            ],
            [
                'nim' => '062140831000',
                'nama' => 'Aditya Pratama',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2003-01-20',
                'email' => 'adityapratama@gmail.com',
                'telepon' => '081234568000',
                'alamat' => 'Jl. Damai No. 5, Jakarta',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.70,
                'nomor_ijazah' => '2021-MI-D3-1000'
            ],
            [
                'nim' => '062140831001',
                'nama' => 'Bella Anjani',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-09-01',
                'email' => 'bellaanjani@gmail.com',
                'telepon' => '081234568001',
                'alamat' => 'Jl. Sejahtera No. 12, Bandung',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.85,
                'nomor_ijazah' => '2021-MI-D3-1001'
            ],
            [
                'nim' => '062140831002',
                'nama' => 'Candra Wijaya',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2003-07-11',
                'email' => 'candrawijaya@gmail.com',
                'telepon' => '081234568002',
                'alamat' => 'Jl. Sentosa No. 20, Surabaya',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.60,
                'nomor_ijazah' => '2021-MI-D3-1002'
            ],
            [
                'nim' => '062140831003',
                'nama' => 'Dina Amelia',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2001-04-25',
                'email' => 'dinaamelia@gmail.com',
                'telepon' => '081234568003',
                'alamat' => 'Jl. Bahagia No. 8, Yogyakarta',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.90,
                'nomor_ijazah' => '2021-MI-D3-1003'
            ],
            [
                'nim' => '062140831004',
                'nama' => 'Eka Putra',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2002-11-03',
                'email' => 'ekaputra@gmail.com',
                'telepon' => '081234568004',
                'alamat' => 'Jl. Harapan No. 30, Semarang',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.75,
                'nomor_ijazah' => '2021-MI-D3-1004'
            ],
            [
                'nim' => '062140831005',
                'nama' => 'Fani Rahayu',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-02-18',
                'email' => 'fanirahayu@gmail.com',
                'telepon' => '081234568005',
                'alamat' => 'Jl. Indah No. 40, Malang',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.80,
                'nomor_ijazah' => '2021-MI-D3-1005'
            ],
            [
                'nim' => '062140831006',
                'nama' => 'Gerry Saputra',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-08-07',
                'email' => 'gerrysaputra@gmail.com',
                'telepon' => '081234568006',
                'alamat' => 'Jl. Abadi No. 15, Medan',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.68,
                'nomor_ijazah' => '2021-MI-D3-1006'
            ],
            [
                'nim' => '062140831007',
                'nama' => 'Hana Lestari',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-05-19',
                'email' => 'hanalestari@gmail.com',
                'telepon' => '081234568007',
                'alamat' => 'Jl. Jaya No. 25, Palembang',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.92,
                'nomor_ijazah' => '2021-MI-D3-1007'
            ],
            [
                'nim' => '062140831008',
                'nama' => 'Irfan Maulana',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2003-03-09',
                'email' => 'irfanmaulana@gmail.com',
                'telepon' => '081234568008',
                'alamat' => 'Jl. Makmur No. 10, Makassar',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.72,
                'nomor_ijazah' => '2021-MI-D3-1008'
            ],
            [
                'nim' => '062140831009',
                'nama' => 'Juwita Putri',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2001-10-14',
                'email' => 'juwitaputri@gmail.com',
                'telepon' => '081234568009',
                'alamat' => 'Jl. Damai Sejati No. 35, Bogor',
                'program_studi' => 'D3 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2024,
                'ipk' => 3.88,
                'nomor_ijazah' => '2021-MI-D3-1009'
            ],
            [
                'nim' => '062140841000',
                'nama' => 'Kevin Pratama',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2003-06-20',
                'email' => 'kevinpratama@gmail.com',
                'telepon' => '081234568010',
                'alamat' => 'Jl. Pelangi No. 7, Jakarta',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.80,
                'nomor_ijazah' => '2021-MI-D4-1000'
            ],
            [
                'nim' => '062140841001',
                'nama' => 'Linda Susanti',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-02-05',
                'email' => 'lindasusanti@gmail.com',
                'telepon' => '081234568011',
                'alamat' => 'Jl. Bintang No. 18, Bandung',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.90,
                'nomor_ijazah' => '2021-MI-D4-1001'
            ],
            [
                'nim' => '062140841002',
                'nama' => 'Miko Hadi',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2003-09-10',
                'email' => 'mikohadi@gmail.com',
                'telepon' => '081234568012',
                'alamat' => 'Jl. Surya No. 28, Surabaya',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.75,
                'nomor_ijazah' => '2021-MI-D4-1002'
            ],
            [
                'nim' => '062140841003',
                'nama' => 'Nia Safitri',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2001-01-15',
                'email' => 'niasafitri@gmail.com',
                'telepon' => '081234568013',
                'alamat' => 'Jl. Bulan No. 9, Yogyakarta',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.95,
                'nomor_ijazah' => '2021-MI-D4-1003'
            ],
            [
                'nim' => '062140841004',
                'nama' => 'Oscar Wijaya',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2002-04-29',
                'email' => 'oscarwijaya@gmail.com',
                'telepon' => '081234568014',
                'alamat' => 'Jl. Langit No. 35, Semarang',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.82,
                'nomor_ijazah' => '2021-MI-D4-1004'
            ],
            [
                'nim' => '062140841005',
                'nama' => 'Putri Lestari',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-08-01',
                'email' => 'putrilestari@gmail.com',
                'telepon' => '081234568015',
                'alamat' => 'Jl. Awan No. 42, Malang',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.88,
                'nomor_ijazah' => '2021-MI-D4-1005'
            ],
            [
                'nim' => '062140841006',
                'nama' => 'Raka Aditya',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-03-17',
                'email' => 'rakaaditya@gmail.com',
                'telepon' => '081234568016',
                'alamat' => 'Jl. Tanah Air No. 20, Medan',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.78,
                'nomor_ijazah' => '2021-MI-D4-1006'
            ],
            [
                'nim' => '062140841007',
                'nama' => 'Sinta Dewi',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-12-22',
                'email' => 'sintadewi@gmail.com',
                'telepon' => '081234568017',
                'alamat' => 'Jl. Nusantara No. 30, Palembang',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.93,
                'nomor_ijazah' => '2021-MI-D4-1007'
            ],
            [
                'nim' => '062140841008',
                'nama' => 'Tio Pratama',
                'mengisi_tracer' => true,
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2003-05-05',
                'email' => 'tiopratama@gmail.com',
                'telepon' => '081234568018',
                'alamat' => 'Jl. Merapi No. 11, Makassar',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.70,
                'nomor_ijazah' => '2021-MI-D4-1008'
            ],
            [
                'nim' => '062140841009',
                'nama' => 'Ulin Nuha',
                'mengisi_tracer' => false,
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2001-07-28',
                'email' => 'ulinnuha@gmail.com',
                'telepon' => '081234568019',
                'alamat' => 'Jl. Semeru No. 23, Bogor',
                'program_studi' => 'D4 Manajemen Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'ipk' => 3.89,
                'nomor_ijazah' => '2021-MI-D4-1009'
            ]
        ]);
    }
}
